# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\table.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TableCheckWindow(object):
    def setupUi(self, TableCheckWindow):
        TableCheckWindow.setObjectName("TableCheckWindow")
        TableCheckWindow.resize(1020, 468)
        self.centralwidget = QtWidgets.QWidget(TableCheckWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 9, 1001, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(".\\价目.png"))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        TableCheckWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TableCheckWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1020, 26))
        self.menubar.setObjectName("menubar")
        TableCheckWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TableCheckWindow)
        self.statusbar.setObjectName("statusbar")
        TableCheckWindow.setStatusBar(self.statusbar)

        self.retranslateUi(TableCheckWindow)
        QtCore.QMetaObject.connectSlotsByName(TableCheckWindow)

    def retranslateUi(self, TableCheckWindow):
        _translate = QtCore.QCoreApplication.translate
        TableCheckWindow.setWindowTitle(_translate("TableCheckWindow", "表格查看"))
import pic_rc
